# Site settings
title: Ghostyii's blog
description: "Ghostyii的个人博客"
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
url: "https://github.com/GhostYii/GhostYii.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'
# User settings
username: Ghostyii
user_title: Ghostyii - 远山长
email: ghostyiigame@outlook.com
twitter_username: null
github_username:  GhostYii
gplus_username:  null
disqus_username: null

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: 主页
    url: /index.html
  - title: 文章列表
    url: /posts/index.html
  - title: 分类
    url: /series/index.html
  - title: 标签
    url: /tags/index.html
  - title: 关于
    url: /about/index.html
# projects in header index
projects:
  - name: InventorySystem
    url: https://github.com/GhostYii/InventorySystem
  - name: MiniMinesweeper
    url: https://github.com/GhostYii/MiniMinesweeper
  - name: Easy Gomoku
    url: https://github.com/GhostYii/Workshop-gomoku
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
